# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, W, killactive,
bind = $mainMod SHIFT, L, exec, systemctl suspend || loginctl suspend
bind = $mainMod, L, exec, loginctl lock-session
bind = $mainMod, E, exec, $fileManager
bind = $mainMod ALT, SPACE, togglefloating,
bind = $mainMod, global, quickshell:toggleLauncher
bind = $mainMod, C, global, quickshell:toggleCalendar
bind = $mainMod SHIFT, C, exec, hyprpicker
bind = $mainMod, J, togglesplit, # dwindle
bind = CTRL SHIFT, escape, exec, $taskManager
bind = $mainMod SHIFT, R, exec, ~/.config/hypr/wf-recorder/record.sh

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-5]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod ALT, S, movetoworkspace, special:magic
bind = $mainMod CTRL, S, movetoworkspace, e+0

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, -1
bind = $mainMod, mouse_up, workspace, +1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Screenshots
bind = ,Print, exec, grim ~/Pictures/Screenshots/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png # Fullscreen screenshot -> ~/Pictures/Screenshots
bind = $mainMod SHIFT,S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png # Select area screenshot with slurp
bind = SUPER,Print, exec, grim -g "$(slurp)" - | wl-copy # Select area screenshot and copy to clipboard

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 2%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = ,XF86AudioNext, exec, playerctl next
bindl = ,XF86AudioPause, exec, playerctl play-pause
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioPrev, exec, playerctl previous

bind = $mainMod, equal, exec, ~/.config/hypr/hypr-zoom/exec.sh
bind = $mainMod, bracketleft, exec, ~/.config/hypr/hyprsunset/increase_sunset.sh
bind = $mainMod, bracketright, exec, ~/.config/hypr/hyprsunset/decrease_sunset.sh
